<?php
$arr =array(
    'accounting' =>array('name'=>'Accounting','icon'=>'markers/accounting.png'),
    'airport'       => array('name'=>'Airport','icon'=>'markers/airport.png'),
    'amusement_park'=> array('name'=>'Amusement park','icon'=>'markers/amusement_park.png'),
    'aquarium'      => array('name'=>'Aquarium','icon'=>'markers/aquarium.png'),
    'art_gallery'   => array('name'=>'Art gallery','icon'=>'markers/art_gallery.png'),
    'atm'           => array('name'=>'Atm','icon'=>'markers/atm.png'),
    'bakery'        => array('name'=>'Bakery','icon'=>'markers/bakery.png'),
    'bank'          => array('name'=>'Bank','icon'=>'markers/bank.png'),
    'bar'           => array('name'=>'Bar','icon'=>'markers/bar.png'),
    'beauty_salon'  => array('name'=>'Beauty salon'),
    'bicycle_store' => array('name'=>'Bicycle store','icon'=>'markers/bicycle_store.png'),
    'book_store'    => array('name'=>'Book store'),
    'bowling_alley' => array('name'=>'Bowling alley'),
    'bus_station'   => array('name'=>'Bus station','icon'=>'markers/bus_station.png'),
    'cafe'          => array('name'=>'Cafe','icon'=>'markers/cafe.png'),
    'campground'    => array('name'=>'Campground','icon'=>'markers/campground.png'),
    'car_dealer'    => array('name'=>'Car dealer'),
    'car_rental'    => array('name'=>'Car rental'),
    'car_repair'    => array('name'=>'Car repair','icon'=>'markers/car_repair.png'),
    'car_wash'      => array('name'=>'Car wash','icon'=>'markers/car_wash.png'),
    'casino'        => array('name'=>'Casino','icon'=>'markers/casino.png'),
    'cemetery'      => array('name'=>'Cemetery','icon'=>'markers/cemetery.png'),
    'church'        => array('name'=>'Church','icon'=>'markers/church.png'),
    'city_hall'     => array('name'=>'City hall','icon'=>'markers/city_hall.png'),
    'clothing_store'=> array('name'=>'Clothing store','icon'=>'markers/clothing_store.png'),
    'convenience_store' => array('name'=>'Convenience store'),
    'courthouse'    => array('name'=>'Courthouse','icon'=>'markers/courthouse.png'),
    'dentist'       => array('name'=>'Dentist'),
    'department_store' => array('name'=>'Department store'),
    'doctor'        => array('name'=>'Doctor'),
    'electrician'   => array('name'=>'Electrician'),
    'electronics_store'=> array('name'=>'Electronics store','icon'=>'markers/electronics_store.png'),
    'embassy'       => array('name'=>'Embassy'),
    'establishment' => array('name'=>'Establishment','icon'=>'markers/establishment.png'),
    'finance'       => array('name'=>'Finance'),
    'fire_station'  => array('name'=>'Fire station','icon'=>'markers/fire_station.png'),
    'florist'       => array('name'=>'Florist'),
    'food'          => array('name'=>'Restaurent','icon'=>'markers/food.png'),
    'funeral_home'  => array('name'=>'Funeral home'),
    'furniture_store' => array('name'=>'Furniture store'),
    'gas_station'   => array('name'=>'Gas station','icon'=>'markers/gas_station.png'),
    'general_contractor' => array('name'=>'General contractor'),
    'grocery_or_supermarket' => array('name'=>'Grocery or supermarket','icon'=>'markers/grocery_or_supermarket.png'),
    'gym'           => array('name'=>'Gym','icon'=>'markers/gym.png'),
    'hair_care'     => array('name'=>'Hair care','icon'=>'markers/hair_care.png'),
    'hardware_store'=> array('name'=>'Hardware store','icon'=>'markers/hardware_store.png'),
    'health'        => array('name'=>'Health','icon'=>'markers/health.png'),
    'hindu_temple'  => array('name'=>'Hindu temple','icon'=>'markers/hindu_temple.png')
);

echo json_encode($arr);